Repository GoodDollar/GoodDAPP, pull requests merged in 2020-05, with the labels that each got.

#1772 fix: usecallbacks & events & logic
  src/lib/hooks/hasConnectionChange.js
Labels: bug

#1810 Update autotests
  cypress.json
  cypress/PageObjects/EditProfilePage.js
  cypress/PageObjects/HomePage.js
  cypress/PageObjects/InvitePage.js
  cypress/PageObjects/ProfilePrivacyPage.js
  cypress/PageObjects/SignUpPage.js
  cypress/PageObjects/StartPage.js
  cypress/PageObjects/SupportPage.js
  cypress/integration/Case1_Sign_up.js
  cypress/integration/Case2_Authorization.js
  cypress/integration/Case3_Profile_editing.js
  cypress/integration/Case4_Menu.js
  cypress/integration/Case4_Menu_header_items.js
  cypress/integration/Case5_Profile_privacy.js
  cypress/integration/Case6_Wallet_backup.js
  cypress/integration/Case7_Send_money.js
  cypress/integration/Case8_Receive_money.js
  src/components/common/buttons/SaveButton.js
Labels: automation

#1843 Update autotests
  cypress/PageObjects/EditProfilePage.js
  cypress/PageObjects/HomePage.js
  cypress/PageObjects/ReceiveMoneyPage.js
  cypress/PageObjects/SendMoneyPage.js
  cypress/fixtures/userMnemonicSave.txt
  cypress/integration/Case1_Sign_up.js
  cypress/integration/Case1_Sign_up_create.js
  cypress/integration/Case7_Send_money.js
  cypress/integration/Case8_Receive_money.js
  cypress/integration/Case9_Sign_up_delete.js
  src/components/common/buttons/SaveButton.js
Labels: automation

#1413 [WIP] Deep Linking for mobile app
  android/app/build.gradle
  android/app/proguard-rules.pro
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/gooddollar/MainActivity.java
  android/app/src/main/java/com/gooddollar/MainApplication.java
  android/gradle.properties
  branch.json
  ios/GoodDollar.xcodeproj/project.pbxproj
  ios/GoodDollar/AppDelegate.m
  ios/GoodDollar/DeepLink+AppDelegate.m
  ios/GoodDollar/GoodDollar.entitlements
  ios/GoodDollar/Info.plist
  ios/Podfile
  ios/Podfile.lock
  native.js
  package-lock.json
  package.json
  src/RouterSelector.js
  src/components/appSwitch/AppSwitch.js
  src/components/dashboard/Dashboard.js
  src/components/dashboard/OutOfGasError.js
  src/init.js
  src/lib/hooks/useAppState.js
  src/lib/utils/deepLinking.native.js
  src/lib/utils/deepLinking.web.js
  src/lib/utils/extractPathname.js
Labels: React Native

#1411 [WIP] Local Push Notifications
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/drawable-hdpi/received_0.png
  android/app/src/main/res/drawable-hdpi/send_0.png
  android/app/src/main/res/drawable-ldpi/received_0.png
  android/app/src/main/res/drawable-ldpi/send_0.png
  android/app/src/main/res/drawable-mdpi/received_0.png
  android/app/src/main/res/drawable-mdpi/send_0.png
  android/app/src/main/res/drawable-xhdpi/received_0.png
  android/app/src/main/res/drawable-xhdpi/send_0.png
  android/app/src/main/res/values/colors.xml
  ios/GoodDollar.xcodeproj/project.pbxproj
  ios/GoodDollar/AppDelegate.h
  ios/GoodDollar/AppDelegate.m
  ios/GoodDollar/Info.plist
  ios/GoodDollar/RNPushNotificationIOS+AppDelegate.m
  ios/Podfile.lock
  native.js
  package-lock.json
  package.json
  src/backgroundFetch.js
  src/components/dashboard/Dashboard.js
  src/components/dashboard/ReceiveByQR.native.js
  src/pushNotifications.js
Labels: React Native

#1937 Fix SendLinkSummary on Native
  src/components/dashboard/SendLinkSummary.js
Labels: React Native
