Repository GoodDollar/GoodDAPP, pull requests merged in 2020-03, with the labels that each got.

#1380 Fix mobile detection & fix Share
  package.json
  src/SignupRouter.js
  src/components/appNavigation/TabsView.js
  src/components/common/animations/SpinnerCheckMark/SpinnerCheckMark.js
  src/components/common/buttons/ShareButton.js
  src/components/common/form/InputText.js
  src/components/common/modal/ModalActionsByFeedType.js
  src/components/common/modal/ModalWrapper.js
  src/components/common/modal/__tests__/ModalOverlay.js
  src/components/common/view/AddWebApp.js
  src/components/common/view/AmountInput.js
  src/components/dashboard/Dashboard.js
  src/components/dashboard/FaceRecognition/Camera.web.js
  src/components/dashboard/FaceRecognition/FRIntro.js
  src/components/dashboard/FaceRecognition/UnsupportedDevice.js
  src/components/dashboard/FeedItems/ListEventItem.js
  src/components/dashboard/FeedModalList.js
  src/components/dashboard/Marketplace.js
  src/components/dashboard/Receive.js
  src/components/dashboard/ReceiveConfirmation.js
  src/components/dashboard/ReceiveSummary.js
  src/components/dashboard/Rewards.js
  src/components/dashboard/SendLinkSummary.js
  src/components/sidemenu/SideMenuPanel.js
  src/components/signup/PhoneForm.js
  src/components/signup/SignupState.js
  src/lib/analytics/bugsnag.native.js
  src/lib/share/index.js
  src/lib/utils/Orientation.js
  src/lib/utils/canShare.js
  src/lib/utils/normalizeText.js
  src/lib/utils/platform.js
Labels: React Native

#1382 Fix CustomButton
  package.json
  src/components/common/buttons/BaseButton.js
  src/components/common/buttons/CustomButton.js
Labels: React Native

#1397 React native claim page
  src/components/common/view/BigGoodDollar.js
  src/components/dashboard/Claim.js
  src/components/dashboard/ClaimButton.js
Labels: React Native

#1410 React native app icons
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  ios/GoodDollar.xcodeproj/project.pbxproj
  ios/GoodDollar/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/GoodDollar/Images.xcassets/AppIcon.appiconset/apple-icon-120x120-1.png
  ios/GoodDollar/Images.xcassets/AppIcon.appiconset/apple-icon-120x120.png
  ios/GoodDollar/Images.xcassets/AppIcon.appiconset/apple-icon-180x180.png
  ios/GoodDollar/Images.xcassets/AppIcon.appiconset/apple-icon-57x57-1.png
  ios/GoodDollar/Images.xcassets/AppIcon.appiconset/apple-icon-57x57.png
  ios/GoodDollar/Images.xcassets/AppIcon.appiconset/apple-icon-60x60.png
  ios/GoodDollar/Images.xcassets/AppIcon.appiconset/apple-icon-76x76-1.png
  ios/GoodDollar/Images.xcassets/AppIcon.appiconset/apple-icon-76x76.png
  ios/GoodDollar/Images.xcassets/AppIcon.appiconset/apple-icon.png
  ios/GoodDollar/Images.xcassets/Contents.json
Labels: React Native

#1409 General fixes for mobile app
  package-lock.json
  package.json
  src/SignupRouter.js
  src/components/about/About.js
  src/components/appNavigation/stackNavigation.js
  src/components/appSwitch/AppSwitch.js
  src/components/auth/Auth.js
  src/components/common/buttons/CustomIcon.js
  src/components/common/form/ImageCropper.native.js
  src/components/common/form/InputRecipient.js
  src/components/common/form/InputText.js
  src/components/common/modal/ModalLeftBorder.native.js
  src/components/common/view/SummaryTable.js
  src/components/common/view/WavesBackground.js
  src/components/dashboard/Dashboard.js
  src/components/dashboard/FaceRecognition/FRIntro.js
  src/components/dashboard/FaceRecognition/UnsupportedDevice.js
  src/components/dashboard/FeedItems/EmptyEventFeed.js
  src/components/dashboard/FeedItems/EventCounterParty.js
  src/components/dashboard/FeedItems/FeedListItem.js
  src/components/dashboard/FeedItems/FeedListItemLeftBorder.native.js
  src/components/dashboard/FeedItems/FeedListItemLeftBorder.web.js
  src/components/dashboard/FeedItems/ListEventItem.js
  src/components/dashboard/FeedModalList.js
  src/components/dashboard/MagicLinkInfo.js
  src/components/dashboard/Marketplace.js
  src/components/dashboard/OutOfGasError.js
  src/components/dashboard/ServiceWorkerUpdatedDialog.js
  src/components/dashboard/Summary.js
  src/components/profile/OptionsRow.js
  src/components/profile/ViewOrUploadAvatar/index.js
  src/components/sidemenu/SideMenuItem.js
  src/components/signup/InvalidWeb3TokenError.js
  src/components/signup/MagicLinkInfo.js
  src/components/signup/SignupState.js
  src/components/splash/Splash.js
  src/init.js
  src/lib/utils/createAppContainer.native.js
  src/lib/utils/createAppContainer.web.js
  src/lib/utils/isTablet.native.js
  src/lib/utils/isTablet.web.js
  src/lib/utils/platform.js
Labels: React Native

#1415 Fix close button of modals [Android]
  src/components/common/modal/ModalCloseButton.js
  src/components/common/modal/ModalContainer.js
Labels: React Native

#1426 Add blank.html for android
  .gitignore
  android/app/src/main/assets/blank.html
Labels: React Native

#1422 Fix react-native-gesture-handle
  ios/GoodDollar.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package-lock.json
  package.json
  patches/react-native-gesture-handler+1.6.0.patch
Labels: React Native

#1367 fix and optimize tests
  cypress.json
  cypress/PageObjects/EditProfilePage.js
  cypress/integration/Case1_Sign_up.js
  cypress/integration/Case3_Profile_editing.js
  cypress/integration/Case4_Menu.js
  cypress/integration/Case4_Menu_header_items.js
Labels: automation

#1407 Fix connection checks
  src/components/common/connectionDialog/internetConnection.js
  src/lib/hooks/hasConnectionChange.js
  src/lib/hooks/useConnection.native.js
  src/lib/hooks/useConnection.web.js
  src/lib/hooks/useConnectionGun.js
  src/lib/hooks/useConnectionWeb3.js
Labels: React Native

#1474 (Bug) [React Native] Fix share payment link
  .env.dev
  android/app/build.gradle
  babel.config.js
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/dashboard/Claim.js
  src/components/dashboard/SendByQR.native.js
  src/config/config.js
  src/config/env.native.js
  src/config/env.web.js
  src/lib/gundb/gundb.native.js
  src/lib/gundb/gundb.web.js
  src/lib/share/index.js
Labels: React Native

#1531 Add animation to TopButton
  src/components/common/animations/Fade/index.js
  src/components/common/buttons/ScrollToTopButton.js
  src/components/dashboard/FeedList.js
Labels: React Native

#1543 Android fonts
  package-lock.json
  src/components/common/modal/ModalPaymentStatus.js
  src/components/common/view/Text.js
  src/components/signup/EmailConfirmation.js
  src/components/signup/EmailForm.js
  src/components/signup/NameForm.js
  src/components/signup/PhoneForm.js
  src/components/signup/SmsForm.js
Labels: React Native, bug
